app = "lara-bomb"
primary_region = "gru"

[env]
SERVER_BIND = "0.0.0.0"
SERVER_PORT = "8000"
SERVER_DEBUG = "false"
SERVER_ACCESS_TOKEN_EXPIRE_MINUTES = "10080"
SERVER_ALGORITHM = "HS256"

[deploy]
release_command = "python -m prisma migrate deploy"

[http_service]
internal_port = 8000
force_https = true
