name: Deploy do Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build \
            --file Dockerfile \
            --tag insper-dev/bomb:latest \
            .

      - name: Remover container antigo (se houver)
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^bomb-insper$'; then
            docker rm -f app
          fi

      - name: Criar volume para banco de dados (se não existir)
        run: |
          if ! docker volume ls --format '{{.Name}}' | grep -q '^bomb_insper_db$'; then
            docker volume create bomb_insper_db
          fi

      - name: Iniciar container com variáveis de ambiente
        env:
          EXTERNAL_PORT: ${{ secrets.EXTERNAL_PORT }}
          SERVER_SECRET_KEY: ${{ secrets.SERVER_SECRET_KEY }}
        run: |
          docker run -d \
            --name bomb-insper \
            --restart always \
            -p ${EXTERNAL_PORT}:8000 \
            -e SERVER_SECRET_KEY \
            -v bomb_insper_db:/app/data \
            insper-dev/bomb:latest
